### ISSUE TITLE
Please push to PyPI

### ISSUE THREAD

**Issue by mvasilkov** [bartTC/django-memcache-status#10]
Please push the latest version to PyPI, since it hosts v1.1 as of now.

**Comment by philgyford** [comment]
Any progress on this? Many thanks.

**Comment by BodhiSukha** [comment]
+1

**Comment by dan-passaro** [comment]
+1, would be great to get these RemovedInDjango19 errors out of our logs without having to fork this project or install from Github... Since #12 is merged in seems like a good time to release.

**Comment by thijstriemstra** [comment]
@bartTC could you push a new release because master is compatible with Django 1.9, 1.1 isn't.

**Comment by bartTC** [comment]
I had issues with Python3 and didn't want to publish it with this error. However that seems to be an upstream error quite deep into `python-memcached`, related ticket is #15.

So I published it now anyway, with a failing Python3 test.

v1.2 is on pypi. https://pypi.python.org/pypi/django-memcache-status/1.2

**Comment by thijstriemstra** [comment]
Thanks!
