### ISSUE TITLE
Debugging memcached_status

### ISSUE THREAD

**Issue by Six-wars** [bartTC/django-memcache-status#13]
I've got memcached_status in the installed apps and previously it was working, I switched django to another database and now it's not showing up. How can I debug why?

**Comment by bartTC** [comment]
To a new database or to a new cache backend? From MySQL to Postgres? Need more info here to reproduce.

**Comment by bartTC** [comment]
Closing, as of no feedback.

**Comment by Six-wars** [comment]
This is a while back I found a solution around it
