### ISSUE TITLE
Google Cloud Bitnami Memcached get_cache_stats timeout

### ISSUE THREAD

**Issue by retosteffen** [bartTC/django-memcache-status#17]
Hi,

Has anyone managed to use this with Google Cloud Bitnami Memcached (with python-memcached)?
I get a timeout error every time and am not sure if it's this app or if there is a problem with my Memcached installation.
Thanks!

**Comment by bartTC** [comment]
I didn't but the code is now logging a WARNING message if the backend doesn't provide any stats.
