### ISSUE TITLE
Document how to integrate memcache-status in your own customized admin index page.

### ISSUE THREAD

**Issue by andybak** [bartTC/django-memcache-status#3]
This isn't a very scalable strategy. Even if I'm not using a customized index page, then all the 3rd party apps that do are going to fight over control.

Maybe the best idea is to document how to customize the index page rather than doing it by default?

**Comment by jtaylor1989** [comment]
After I add memcache_status to my installed apps I get the following error when I try to access my Django admin page:
File "/Users/comp/Desktop/Dev/educa/lib/python3.6/site-packages/memcache_status/templatetags/memcache_status_tags.py", line 106, in prettyname
    return ' '.join([word.capitalize() for word in name.split('_')])
TypeError: a bytes-like object is required, not 'str'.

**Comment by bartTC** [comment]
This has been fixed in v2.0. The app no longer automatically sets the index template. It's documented and straightforward how to place the statistics anywhere.
