### ISSUE TITLE
Not showing in admin interface

### ISSUE THREAD

**Issue by jakespeers** [bartTC/django-memcache-status#30]
Can't seem to get this working since upgrading to django 3.2. Has anyone else managed? It seemed to be working before upgrading. Won't show in django admin now.
Thanks

**Comment by DevWoody856** [comment]
I am also suffering from this problem now.

**Comment by bartTC** [comment]
The old release wasn't compatible with latest Django 3.2, v2.3 is now.

https://pypi.org/project/django-memcache-status/2.3/

Please see the installation instructions.
